version: "2.2"

services:
  mongo:
    container_name: mongo
    image: recruit-mongo:latest
    build:
      context: .
      dockerfile: ./.docker/mongo.dockerfile
    env_file:
      - ./.docker/env/mongo.env
    networks:
      - recruit-network
    ports:
      - 27017:27017

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    container_name: elastic
    environment:
      - cluster.name=muggle-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - recruit-network

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    container_name: kibana  
    ports:
      - 5601:5601
    links:
      - elasticsearch1:elasticsearch
    networks:
      - recruit-network

  logstash:
    image: recruit-logstash:latest
    build:
      context: .
      dockerfile: ./.docker/logstash.dockerfile
    container_name: logstash  
    links:
      - elasticsearch1:elasticsearch
      - redis
    networks:
      - recruit-network

  redis:
    image: redis:latest
    container_name: redis  
    ports:
      - 6379:6379
    networks:
      - recruit-network

volumes:
  esdata1:
    driver: local

networks:
  recruit-network:
    driver: bridge